all: barbarian1.pdf barbarian2.pdf bard1.pdf bard2.pdf cleric1.pdf cleric2.pdf druid1.pdf druid2.pdf fighter1.pdf fighter2.pdf monk1.pdf monk2.pdf ranger1.pdf ranger2.pdf ranger3.pdf rogue1.pdf rogue2.pdf sorceror1.pdf sorceror2.pdf warlock1.pdf warlock2.pdf wizard1.pdf wizard2.pdf multiclass1.pdf multiclass2.pdf

redo: clobber all

%.pdf: %.py
	makesheets $<
